---
# Configure apache for serving our application

- name: Enable our required apache modules
  apache_module: name={{ item }} state=present
  with_items:
    - env
    - setenvif
    - headers
    - expires
    - alias
    - rewrite
    - proxy
    - proxy_http
    - vhost_alias
  notify:
    - restart apache

- name: Check our SSL certs directory
  file: dest=/etc/apache2/ssl state=directory mode=0644

- name: Install SSL Cert and key
  copy: src={{ item }} dest=/etc/apache2/ssl
  with_items:
    - apache.crt
    - apache.key

- name: Load the SSL module to use our new certs
  apache_module: name=ssl state=present

- name: Install apache vhost config
  copy: src=mozilla-kuma-apache.conf dest=/etc/apache2/conf.d
