---
# Configure apache for serving our application

- name: Install Apache
  apt: name=apache2 state=present

- name: Enable our required apache modules
  command: /usr/sbin/a2enmod {{ item }}
  with_items:
    - env
    - setenvif
    - headers
    - expires
    - alias
    - rewrite
    - proxy
    - proxy_http
    - vhost_alias
  notify:
    - restart apache

- name: Check our SSL certs directory
  file: dest=/etc/apache2/ssl state=directory mode=0644

- name: Install SSL Cert and key
  copy: src={{ item }} dest=/etc/apache2/ssl
  with_items:
    - apache.crt
    - apache.key

# XXX this doesn't work
#- name: Load the SSL module to use our new certs
#  apache2_module: name=ssl state=present
#  notify:
#    - restart apache

- name: Install apache vhost config
  copy: src=mozilla-kuma-apache.conf dest=/etc/apache2/conf.d

- name: Link uploads directory
  file:
    src=/home/vagrant/uploads
    dest=/home/vagrant/src/media/uploads
    state=link

- name: Link webroot .htaccess
  file:
    name=/home/vagrant/src/webroot/.htaccess
    src=/home/vagrant/src/configs/htaccess-without-mindtouch
    state=link

- name: Link www .htaccess
  file:
    name=/var/www/.htaccess
    src=/home/vagrant/src/configs/htaccess-without-mindtouch
    state=link
