---
# Tasks for configuring our python application execution environment

- name: Remove system packages that could conflict with our deps
  apt: name={{ item }} state=absent
  with_items:
    - python-setuptools
    - python-virtualenv
    - python-pip
    - python-imaging
    - python-mysqldb
    - python-pylibmc
    - python-jinja2
    - python-coverage
    - ipython
    - python-sqlparse
    - python-pyquery
    - python-pygments
    - pylint
    - pyflakes

# XXX Is the mysql db connector installed here, or in an earlier step?
- name: Add libraries necessary to build the MySQL DB client
  apt: name=libmysqlclient-dev state=present        
    
- name: Create a wheels cache directory
  file: dest=/home/vagrant/src/puppet/cache/wheels state=directory

#- name: Install pip
#  apt: name=python-pip

- name: Install python-virtualenv package
  apt: name=python-virtualenv

- name: Install our specific version of Django
  pip: name=Django version=1.4.9

- name: Download the mozilla wheels tarball
  get_url:
    url=https://s3-us-west-2.amazonaws.com/pkgs.mozilla.net/python/mdn/base_wheels.tar.gz
    dest=/home/vagrant/src/puppet/cache/wheels/base_wheels.tar.gz
    #force=yes

- name: Unpack our new wheels
  command:
    chdir=/home/vagrant/src/puppet/cache/wheels
    /bin/tar xzvf base_wheels.tar.gz

- name: Create our virtualenv if it doesn't already exist
  sudo: false
  command:
    creates=/home/vagrant/env
    /usr/bin/virtualenv --python=/usr/bin/python2.6 /home/vagrant/env

- name: Upgrade virtualenv pip to the latest release of pip
  pip:
    name=pip
    state=latest
    virtualenv=/home/vagrant/env

- name: Install wheel
  sudo: false
  pip: name=wheel state=present virtualenv=/home/vagrant/env

- name: XXX Download pyelasticsearch separately until it's included in wheels
  sudo: false
  pip: name=pyelasticsearch version=0.6.1 virtualenv=/home/vagrant/env

- name: XXX Hack prod.txt to remove the busted django-mozilla-product-details
  shell:
        chdir=/home/vagrant/src
        cp requirements/prod.txt requirements/prod.hacked.txt && sed -i -e 's/django-mozilla-product-details@5a59a50b2f49f4ff555e87ebecc4fe690e71e7b0/django-mozilla-product-details@515d55ddf20688c71b54d77eb157eaee21214859/' requirements/prod.hacked.txt

- name: XXX Hack prod.txt to remove the pystatsd - we don't use statsd any more?
  shell:
        chdir=/home/vagrant/src
        sed -i -e '/pystatsd/d' requirements/prod.hacked.txt

- name: Install kuma requirements from wheels
  sudo: false
  pip:
    requirements={{ item }}
    chdir=/home/vagrant/src
    executable=/home/vagrant/env/bin/pip
    extra_args='--no-index --find-links=file:///home/vagrant/src/puppet/cache/wheels/base_wheels'
    virtualenv=/home/vagrant/env
  with_items:
    - requirements/prod.hacked.txt
    - requirements/dev.txt
    - requirements/compiled.txt

- name: XXX Clean up our hacks
  file: name=/home/vagrant/src/requirements/prod.hacked.txt state=absent
  